### ISSUE TITLE
No Alarms being triggered in latest basic deployment from staging.suite.com

### ISSUE THREAD

**Issue by corywink** [Azure/telemetry-agent-dotnet#24]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

I just deployed from staging.suite.com: https://coryignite0925.azurewebsites.net/dashboard
I don't see any alarms being triggered after more than 30 mins of the solution running
I see telemetry and devices on the map, as well as seed data rules and devices, but none of the alarms are being triggered.

**Comment by timlaverty** [comment]
dup of https://github.com/Azure/device-simulation-dotnet/issues/60
